server:
  port: 8080

spring:
  profiles:
    active: dev

---
server:
  port: 8086

spring:
  config:
    activate:
      on-profile: prod

---
server:
  port: 8087

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    username: root
    password: lw987654321
    url: jdbc:mysql://127.0.0.1:3306/dev
    driver-class-name: com.mysql.cj.jdbc.Driver

  spring:
    aop:
      auto: true

  mybatis:
    # 指定 mapper.xml 的位置
    mapper-locations: classpath:com/example/demo/dao/*.xml
    #扫描实体类的位置,在此处指明扫描实体类的包，在 mapper.xml 中就可以不写实体类的全路径名
    type-aliases-package: com.example.demo.dao
    configuration:
      #默认开启驼峰命名法，可以不用设置该属性
      map-underscore-to-camel-case: true

