server:
  port: 8080

spring:
  profiles:
    active: dev

---
server:
  port: 8086

spring:
  config:
    activate:
      on-profile: prod

---
server:
  port: 8087

spring:
  config:
    activate:
      on-profile: dev
